move_group:
  ros__parameters:
    robot_description_planning:
      joint_limits:
        left_joint_1:
          has_velocity_limits: true
          max_velocity: 0.392699081698724
          has_acceleration_limits: true
          max_acceleration: 0.197335651876739
        left_joint_2:
          has_velocity_limits: true
          max_velocity: 0.261799387799149
          has_acceleration_limits: true
          max_acceleration: 0.168446962097729
        left_joint_3:
          has_velocity_limits: true
          max_velocity: 0.285832571599111
          has_acceleration_limits: true
          max_acceleration: 0.207088551736883
        left_joint_4:
          has_velocity_limits: true
          max_velocity: 0.392699081698724
          has_acceleration_limits: true
          max_acceleration: 0.209664657712827
        left_joint_5:
          has_velocity_limits: true
          max_velocity: 0.302168853397778
          has_acceleration_limits: true
          max_acceleration: 0.237228642589573
        left_joint_6:
          has_velocity_limits: true
          max_velocity: 0.628318530717959
          has_acceleration_limits: true
          max_acceleration: 0.335103216382911

        right_joint_1:
          has_velocity_limits: true
          max_velocity: 0.392699081698724
          has_acceleration_limits: true
          max_acceleration: 0.197335651876739
        right_joint_2:
          has_velocity_limits: true
          max_velocity: 0.261799387799149
          has_acceleration_limits: true
          max_acceleration: 0.168446962097729
        right_joint_3:
          has_velocity_limits: true
          max_velocity: 0.285832571599111
          has_acceleration_limits: true
          max_acceleration: 0.207088551736883
        right_joint_4:
          has_velocity_limits: true
          max_velocity: 0.392699081698724
          has_acceleration_limits: true
          max_acceleration: 0.209664657712827
        right_joint_5:
          has_velocity_limits: true
          max_velocity: 0.302168853397778
          has_acceleration_limits: true
          max_acceleration: 0.237228642589573
        right_joint_6:
          has_velocity_limits: true
          max_velocity: 0.628318530717959
          has_acceleration_limits: true
          max_acceleration: 0.335103216382911
          
        joint_1:
          has_velocity_limits: true
          max_velocity: 0.392699081698724
          has_acceleration_limits: true
          max_acceleration: 0.197335651876739
        joint_2:
          has_velocity_limits: true
          max_velocity: 0.261799387799149
          has_acceleration_limits: true
          max_acceleration: 0.168446962097729
        joint_3:
          has_velocity_limits: true
          max_velocity: 0.285832571599111
          has_acceleration_limits: true
          max_acceleration: 0.207088551736883
        joint_4:
          has_velocity_limits: true
          max_velocity: 0.392699081698724
          has_acceleration_limits: true
          max_acceleration: 0.209664657712827
        joint_5:
          has_velocity_limits: true
          max_velocity: 0.302168853397778
          has_acceleration_limits: true
          max_acceleration: 0.237228642589573
        joint_6:
          has_velocity_limits: true
          max_velocity: 0.628318530717959
          has_acceleration_limits: true
          max_acceleration: 0.335103216382911

