/**:
  ros__parameters:
    namespace: left_
    walls:
      - "{id: wall_1, pose: [1.0, 0.5, 1.0, 1.5708, 0.0, 0.0], size: [0.01, 5.0, 2.0]}"
      - "{id: wall_2, pose: [1.0, -0.5, -0.01, 1.5708, 1.5708, 0.0], size: [0.01, 5.0, 2.0]}"
